Add getters in revision
wikimedia/wikimedia-android-data-client pull request #5
Opened 2019-03-29 15:00 UTC by maskaravivek

Commons also needs `revid` and `user` in `Revision`. 

https://github.com/commons-app/apps-android-commons/pull/2714/files#diff-c4388704eae4a67ed6765a7acca79405

2019-03-29 19:14 UTC, dbrant requested changes

2019-03-29 19:14 UTC, dbrant commented on src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
> +        @SerializedName("user") private String user;
Don't need `SerializedName` if it's the same as the field name.

2019-03-29 19:14 UTC, dbrant commented on src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
> +        @SerializedName("revid") private String revisionId;
This can be a `long`, and doesn't need to be a String.

2019-03-29 19:14 UTC, dbrant commented on src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
> +        public String getUser() {
Please annotate these return values as `@Nullable` if you're OK with getting a null value, or make it `@NonNull` and return `StringUtils.defaultString(user)`.

2019-03-30 04:29 UTC, maskaravivek commented
Thanks for reviewing it @dbrant. I have made the requested changes.

2019-04-01 12:40 UTC, merged